// ==UserScript==
// @name         eobadeung replace
// @namespace    http://tampermonkey.net/
// @version      0.3
// @description  RIDI CAN'T STOP ME
// @author       chujuchuchu
// @match        https://view.ridibooks.com/books/425*
// @icon         https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://ridibooks.com&size=64
// @updateURL    https://github.com/chujuchuchu/tamperidi/blob/main/eobadeung%20replace.user.js
// @downloadURL  https://github.com/chujuchuchu/tamperidi/blob/main/eobadeung%20replace.user.js
// @grant        none
// ==/UserScript==

(function() {

    setTimeout(function() {

        var namesreplace = names;
        var totalnames = namesreplace.length;

        var hangulnames = [];
        hangulnames.length = namesreplace.length;

        var romannames = [];
        romannames.length = namesreplace.length;

        for (let i = 0; i < namesreplace.length; i++) {
            let splittext = namesreplace[i].split(",");
            let punctreplace = splittext[0].replaceAll("([[:punct:]])","([^A-za-z\uac00-\ud7af]|[\u1100-\u11ff]|[\u3130-\u318f]|[\ua960-\ua97f]|[\ud7b0-\ud7ff])");
            let regtext = new RegExp(punctreplace.replaceAll("(\w)","([A-za-z\uac00-\ud7af]|[\u1100-\u11ff]|[\u3130-\u318f]|[\ua960-\ua97f]|[\ud7b0-\ud7ff])"), "g");

            hangulnames[i] = regtext;
            romannames[i] = splittext[1];
        }


        var txtWalker = document.createTreeWalker (
            document.body,
            NodeFilter.SHOW_TEXT,
            { acceptNode: function (node) {
                if (node.nodeValue.trim() ) {
                    return NodeFilter.FILTER_ACCEPT; }

                return NodeFilter.FILTER_SKIP;
            }
            },

            false
        );

        var txtNode = null;

        while (txtNode = txtWalker.nextNode () ) {
            var oldTxt = txtNode.nodeValue;

            for (let i = 0; i < totalnames; i++) {
                oldTxt = oldTxt.replaceAll(hangulnames[i], romannames[i]);
            }

            txtNode.nodeValue = oldTxt;
        }




    }, 2000);


})();

var names = ["박무현,Park Moohyun",
             "무현,Moohyun",
             "(\w)Moohyun,$1무현",
             "신해량,Shin Haeryang",
             "해량,Haeryang",
             "(\w)Haeryang,$1해량",
             "강수정,Kang Soojung",
             "수정,Soojung",
             "(\w)Soojung,$1수정",
             "서지혁,Seo Jihyuk",
             "지혁,Jihyuk",
             "(\w)Jihyuk,$1지혁",
             "백애영,Baek Aeyoung",
             "애영,Aeyoung",
             "(\w)Aeyoung,$1애영",
             "이지현,Lee Jihyun",
             "지현,Jihyun",
             "(\w)Jihyun,$1지현",
             "정상현,Jung Sanghyun",
             "상현,Sanghyun",
             "(\w)Sanghyun,$1상현",
             "김재희,Kim Jaehee",
             "재희,Jaehee",
             "(\w)Jaehee,$1재희",
             "김가영,Kim Gayoung",
             "가영,Gayoung",
             "(\w)Gayoung,$1가영",
             "조동희,Cho Donghee",
             "동희,Donghee",
             "(\w)Donghee,$1동희",
             "하이윤,Hai Yun",
             "(\w)Hai Yun,$1이윤",
             "리웨이,Li Wei",
             "(\w)Li Wei,$1웨이",
             "쯔쉬안,Zi Xuan",
             "(\w)Zi Xuan,$1쉬안",
             "하오란,Hao Ran",
             "(\w)Hao Ran,$1오란",
             "웨이치,Wei Qi",
             "(\w)Wei Qi,$1이치",
             "홍타오,Hong Tao",
             "(\w)Hong Tao,$1타오",
             "슈란,Shu Ran",
             "(\w)Shu Ran,$1슈란",
             "수혁,Soohyuk",
             "(\w)Soohyuk,$1수혁",
             "사토,Sato",
             "(\w)Sato,$1사토",
             "센루,Senru",
             "(\w)Senru,$1센루",
             "케빈,Kevin",
             "(\w)Kevin,$1케빈",
             "윌슨,Wilson",
             "(\w)Wilson,$1윌슨",
             "미첼,Mitchell",
             "(\w)Mitchell,$1미첼",
             "미셸,Michelle",
             "(\w)Michelle,$1미셸",
             "마크,Mark",
             "(\w)Mark,$1마크",
             "폴란,Polan",
             "(\w)Polan,$1폴란",
             "리암,Liam",
             "(\w)Liam,$1리암",
             "해리,Harry",
             "(\w)Harry,$1해리",
             "우즈,Woods",
             "(\w)Woods,$1우즈",
             "잭,Jack",
             "(\w)Jack,$1잭",
             "썸머,Summer",
             "(\w)Summer,$1썸머",
             "존스,Jones",
             "(\w)Jones,$1존스",
             "릴리,Lily",
             "(\w)Lily,$1릴리",
             "말론,Malone",
             "(\w)Malone,$1말론",
             "로이,Roy",
             "(\w)Roy,$1로이",
             "굿맨,Goodman",
             "(\w)Goodman,$1굿맨",
             "카터,Carter",
             "(\w)Carter,$1카터",
             "다넬,Darnell",
             "(\w)Darnell,$1다넬",
             "샘,Sam",
             "(\w)Sam,$1샘",
             "카누,Kano",
             "(\w)Kano,$1카누",
             "로건,Logan",
             "(\w)Logan,$1로건",
             "엠마,Emma",
             "(\w)Emma,$1엠마",
             "조셉,Joseph",
             "(\w)Joseph,$1조셉",
             "랜들,Randall",
             "(\w)Randall,$1랜들",
             "밀러,Miller",
             "(\w)Miller,$1밀러",
             "이반,Ivan",
             "(\w)Ivan,$1이반",
             "마틴,Martin",
             "(\w)Martin,$1마틴",
             "휘버,Hubert",
             "(\w)Hubert,$1휘버",
             "자말,Jamal",
             "(\w)Jamal,$1자말",
             "그린,Green",
             "(\w)Green,$1그린",
             "안나,Anna",
             "(\w)Anna,$1안나",
             "헨리,Henry",
             "(\w)Henry,$1헨리",
             "수혁,Sooyhuk",
             "(\w)Sooyhuk,$1수혁",
             "이빈,Lee Bin",
             "(\w)Lee Bin,$1이빈",
             "위버,Weaver",
             "(\w)Weaver,$1위버",
             "바트,Bart",
             "(\w)Bart,$1바트",
             "네브,Nev",
             "(\w)Nev,$1네브",
             "미르,Mir",
             "(\w)Mir,$1미르",
             "앨빈,Alvin",
             "(\w)Alvin,$1앨빈",
             "신카이,Shinkai",
             "(\w)Shinkai,$1카이",
             "자오룽,Zhao Long",
             "(\w)Zhao Long,$1오룽",
             "유금이,Yoo Geumyi",
             "류스케,Ryusuke",
             "타마키,Tamaki",
             "유즈루,Yuzuru",
             "스미레,Sumire",
             "야마시타,Yamashita",
             "히카루,Hikaru",
             "이치타,Ichita",
             "유우키,Yuuki",
             "스즈키,Suzuki",
             "타카하시,Takahashi",
             "유리에,Yurie",
             "블라디미르,Vladimir",
             "세르게예비치,Sergeevich",
             "이바노프,Ivanov",
             "니키타,Nikita",
             "니콜라이,Nikolai",
             "소피야,Sophia",
             "빅토르,Victor",
             "바실예프,Vasiliev",
             "이리나,Irina",
             "바체슬라보브나,Vacheslavovna",
             "무라흐타에바,Murktaeva",
             "드미트리,Dmitry",
             "안드레예비치,Andreyevich",
             "무라토프,Muratov",
             "제니퍼,Jennifer",
             "스미스,Smith",
             "레너드,Leonard",
             "샌더스,Sanders",
             "대니얼,Daniel",
             "로드리게스,Rodriguez",
             "로페즈,Lopez",
             "바트에르덴,Barton",
             "보르지긴,Borjigin",
             "올리버,Oliver",
             "사이먼,Simon",
             "마커스,Marcus",
             "리차드,Richard",
             "헤일리,Hayley",
             "타일러,Tyler",
             "카밀라,Camilla",
             "빅토리아,Victoria",
             "안젤라,Angela",
             "벨리알,Belial",
             "라일리,Riley",
             "장우이,Zhang Yi",
             "마르티나,Martina",
             "산체스,Sanchez",
             "제임스,James",
             "샘 영,Sam Young",
             "은자디,Njadi",
             "벤자민,Benjamin",
             "더스틴,Dustin",
             "존 도우,John Doe",
             "윌리엄,William",
             "에릭슨,Erikson",
             "카를로스,Carlos",
             "루이즈,Luiz",
             "그레이엄,Graham",
             "라파엘,Raphael",
             "야니크,Yannick",
             "투마나코,Tumanako",
             "오란가,Oranga",
             "후미코,Fumiko",
             "에밀리,Emily",
             "프리야,Priya",
             "쿠마리,Kumari",
             "엘리엇,Elliot",
             "브라운,Brown",
             "파멜라,Pamela",
             "왕웨이,Wang Wei",
             "올리비에,Olivier",
             "마이클,Michael",
             "로아커,Roarker",
             "엘리자베스,Elizabeth",
             "로널드,Ronald",
             "와이스,Weiss",
             "데이비드,David",
             "나이트,Knight",
             "가르시아,Garcia",
             "네바에,Neva",
             "홉킨스,Hopkins",
             "타말키,Tamarky",
             "보스턴,Boston",
             "심청이,Shim Chungyi",
             "첼로니,Celloni",
             "랭커스터,Lancaster",
             "마리스,MARIS",
             "씬해량,Sshin Haeryang",
             "신([[:punct:]]),Shin$1",
             "(\w)Shin,$1신",
             "히이윤,Hai Yun",
             "금이씨,Geumyi-ssi",
             "금이 씨,Geumyi-ssi",
             "금이님,Geumyi-nim",
             "금이 님,Geumyi-nim",
             "금이야,Geumyi-ya",
             "케빈 로이,Kevin Roy",
             "루카스,Lucas",
             "은라디,Nradi",
             "아서 굿맨,Arthur Goodman",
             "무한Infinity교,Ininityism",
             "무한교,Infinityism",
             "엘리자베스 위버,Elizabeth Weaver",
             "러시아,Russia",
             "가팀,Ga-team",
             "나팀,Na-team",
             "다팀,Da-team",
             "라팀,Ra-team",
             "마팀,Ma-team",
             "바팀,Ba-team",
             "사팀,Sa-team",
             "아팀,Ah-team",
             "해저기지,Undersea Station",
             "대한도,Daehan Island",
             "중앙동,Center Building",
             "청룡동,Cheongryong Building",
             "백호동,Baekho Building",
             "주적동,Joojeok Building",
             "현무동,Hyunmoo Building",
             "미스터 팍,Mr. Park",
             "미스터 씬,Mr. Shin",
             "신팀장,Team Leader Shin",
             "신 팀장,Team Leader Shin",
             "강부팀장,Deputy Chief Kang",
             "강 부팀장,Deputy Chief Kang",
             "(\w)Yurie,$1유리에",
             "우에하라,Uehara",
             "치과 선생님,dentist seongsaeng-nim",
             "베스,Beth",
             "리즈,Liz",
             "캐새키,Kaesaeki",
             "비나이,Vienna",
             "(\w)Vienna,$1비나이",
             "구원자님,Savior-nim",
             "서찌혁,Seo Jjihyuk",
             "아씨([[:punct:]]),Ah ssi!",
             "Jihyuk이 혀엉,Jihyuk-ie hyuung",
             "Kang Soojung 부팀장,Deputy Chief Kang Soojung",
             "Shin Haeryang 팀장,Team Leader Shin Haeryang",
             "부팀장님,Deputy Chief-nim",
             "팀장님,Team Leader-nim",
             "이씨,Ee ssi",
             "아리아,Aria",
             "프레이저,Frazier",
             "얼씨구? 구원자?,얼씨구? Savior?",
             "Shin Haeryang 선장,Captain Shin Haeryang",
             "Sato 팀장,Team Leader Sato",
             "소피아,Sophia",
             "로런트,Laurent",
             "신부팀장,Deputy Chief Shin",
             "랜덤,Reindom",
             "이서인,Lee Seoin",
             "서인,Seoin",
             "(\w)Seoin,$1서인",
             "류웨이,Liu Wei",
             "뭐 유단자라고 했는데,I said it's a talented person",
             "미스터 랜들,Mr. Randall",
             "이마를 앞 유리에 박았는지",
             "방무연,Bang Mooyeon",
             "양팀장,Team Leader Yang",
             "조부팀장,Deputy Chief Cho",
             "조팀장,Team Leader Cho",
             "선장 Shin Haeryang,Captain Shin Haeryang",
             "부선장 Kim Jaehee,Vice Captain Kim Jaehee",
             "연구원 Park Moohyun,Resarcher Park Moohyun",
             "허허허,Hahaha",




                 ];
